### ISSUE TITLE
Pass data to view?

### ISSUE THREAD

**Issue by h4ckedneko** [brayniverse/laravel-route-macros#1]
Hello @brayniverse, thanks for this useful package.

I'm making a SPA with only one Laravel Blade view and I want to dynamically change the path of CSS and JS in the view because I'm separating the assets for the store and dashboard.

I want to suggest a feature where we can pass a data to the view.

Example:
```php
// routes/store.php
Route::view('/{capture}', 'inferno', ['app' => 'store']);

// routes/dashboard.php
Route::view('/{capture}', 'inferno', ['app' => 'dashboard']);
```

**Comment by brayniverse** [comment]
Hi @h4ckedneko, thanks for using this package and I'm glad you're finding it useful.

While I see the benefit to your particular use case, I don't want to commit to changing to public API to support this within the package. Nevertheless, for your use care the functionality already exists within Laravel.

```php
// routes/store.php
Route::view('/{capture}', 'inferno')->defaults('app', 'store');

// a view somewhere (or anywhere in your app)
request()->route('app'); // store
```

**Comment by h4ckedneko** [comment]
Oh, we can pass using the `defaults` function of Laravel.

I ended up using the layout and stacks. Thanks for the response @brayniverse.

**Comment by brayniverse** [comment]
That's definitely how I would have gone about doing it. Glad you found a solution that works for you.
